<a href="https://colab.research.google.com/github/nuratikafadillah6222-cloud/pemograman-dasar/blob/main/latihan_cleaning_EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Kode tersebut digunakan untuk memanggil beberapa library penting dalam analisis data. `numpy` (disingkat `np`) digunakan untuk mengolah data numerik seperti array dan perhitungan matematika. `pandas` (disingkat `pd`) digunakan untuk mengolah data dalam bentuk tabel atau DataFrame sehingga lebih mudah dibaca dan dianalisis. `matplotlib.pyplot` (disingkat `plt`) berfungsi untuk membuat berbagai jenis grafik seperti garis, batang, atau scatter plot. Sementara itu, `seaborn` (disingkat `sns`) digunakan untuk membuat visualisasi data yang lebih rapi dan menarik dibandingkan matplotlib standar. Secara keseluruhan, keempat library ini sering digunakan bersama dalam proses analisis data karena saling melengkapi satu sama lain.


Memuat tabel customers

In [ ]:
customers_df =pd.read_csv("/content/drive/MyDrive/ pemrograman dasar/data/customers.csv")
customers_df.head()

customer_id customer_name             gender  age  \
0            1       fulan 1             Female   30   
1            2       fulan 2  Prefer not to say   69   
2            3       fulan 3  Prefer not to say   59   
3            4       fulan 4  Prefer not to say   67   
4            5       fulan 5  Prefer not to say   30   

                     home_address  zip_code               city  \
0  8606 Victoria TerraceSuite 560      5464      Johnstonhaven   
1      8327 Kirlin SummitApt. 461      8223    New Zacharyfort   
2       269 Gemma SummitSuite 109      5661           Aliburgh   
3       743 Bailey GroveSuite 141      1729  South Justinhaven   
4         48 Hyatt ManorSuite 375      4032     Griffithsshire   

                          state    country  
0            Northern Territory  Australia  
1               South Australia  Australia  
2  Australian Capital Territory  Australia  
3                    Queensland  Australia  
4                    Queensland  Australia

Kode tersebut digunakan untuk membaca file data dan menampilkannya. Baris pertama, `customers_df = pd.read_csv("/content/drive/MyDrive/ pemrograman dasar/data/customers.csv")`, berfungsi untuk memuat file **customers.csv** ke dalam sebuah **DataFrame** bernama `customers_df` menggunakan library Pandas. DataFrame adalah bentuk tabel yang berisi baris dan kolom, sehingga memudahkan analisis data. Baris kedua, `customers_df.head()`, digunakan untuk menampilkan **5 baris pertama** dari data tersebut. Fungsi ini membantu memastikan bahwa file berhasil dibaca serta melihat struktur awal data seperti nama kolom dan contoh isi datanya.


Memuat tabel orders

In [ ]:
orders_df =pd.read_csv("/content/drive/MyDrive/ pemrograman dasar/data/orders.csv")
orders_df.head()

order_id  customer_id  payment order_date delivery_date
0         1           64    30811  2021-8-30    2021-09-24
1         2          473    50490   2021-2-3    2021-02-13
2         3          774    46763  2021-10-8    2021-11-03
3         4          433    39782   2021-5-6    2021-05-19
4         5          441    14719  2021-3-23    2021-03-24

Kode tersebut digunakan untuk membaca dan menampilkan sebagian data dari file **orders.csv**. Baris pertama, `orders_df = pd.read_csv("/content/drive/MyDrive/ pemrograman dasar/data/orders.csv")`, berfungsi untuk memuat file CSV tersebut ke dalam sebuah **DataFrame** bernama `orders_df` menggunakan Pandas. DataFrame ini menyimpan data dalam bentuk tabel sehingga mudah dianalisis. Baris kedua, `orders_df.head()`, digunakan untuk menampilkan **5 baris pertama** dari data yang sudah dimuat. Hal ini membantu memastikan bahwa file berhasil terbaca serta memberikan gambaran awal tentang struktur dan isi datanya.


memuat tables product

In [ ]:
products_df =pd.read_csv("/content/drive/MyDrive/ pemrograman dasar/data/products.csv")
products_df.head()

product_id product_type  product_name size colour  price  quantity  \
0           0        Shirt  Oxford Cloth   XS    red    114        66   
1           1        Shirt  Oxford Cloth    S    red    114        53   
2           2        Shirt  Oxford Cloth    M    red    114        54   
3           3        Shirt  Oxford Cloth    L    red    114        69   
4           4        Shirt  Oxford Cloth   XL    red    114        47   

                                    description  
0  A red coloured, XS sized, Oxford Cloth Shirt  
1   A red coloured, S sized, Oxford Cloth Shirt  
2   A red coloured, M sized, Oxford Cloth Shirt  
3   A red coloured, L sized, Oxford Cloth Shirt  
4  A red coloured, XL sized, Oxford Cloth Shirt

Kode tersebut digunakan untuk memuat dan melihat sebagian data dari file **products.csv**. Pada baris pertama, `products_df = pd.read_csv("/content/drive/MyDrive/ pemrograman dasar/data/products.csv")`, program membaca file CSV tersebut dan menyimpannya dalam sebuah **DataFrame** bernama `products_df`, yang berbentuk tabel berisi baris dan kolom. Baris kedua, `products_df.head()`, digunakan untuk menampilkan **5 baris pertama** dari tabel tersebut. Tujuannya adalah untuk memastikan data berhasil dimuat serta mengetahui struktur awal data, seperti nama kolom dan contoh isi produknya.


Memuat tabel sales

In [ ]:
sales_df =pd.read_csv("/content/drive/MyDrive/ pemrograman dasar/data/sales.csv")
sales_df.head()

sales_id  order_id  product_id  price_per_unit  quantity  total_price
0         0         1         218             106         2        212.0
1         1         1         481             118         1        118.0
2         2         1           2              96         3        288.0
3         3         1        1002             106         2        212.0
4         4         1         691             113         3        339.0

Kode tersebut digunakan untuk membaca data penjualan dan menampilkan sebagian isinya. Baris pertama, `sales_df = pd.read_csv("/content/drive/MyDrive/ pemrograman dasar/data/sales.csv")`, berfungsi untuk memuat file **sales.csv** ke dalam sebuah **DataFrame** bernama `sales_df`, yaitu struktur data berbentuk tabel yang memudahkan proses analisis. Baris kedua, `sales_df.head()`, menampilkan **5 baris pertama** dari DataFrame tersebut. Ini dilakukan untuk memastikan bahwa data berhasil terbaca dengan benar serta memberikan gambaran awal mengenai isi dan struktur data penjualan.


**Assessing Data**
Sekarang masuk ke tahap kedua dalam proses data wrangling yaitu assessing data.

**Menilai Data customers_df**
Data pertama yang akan kita nilai adalah `customers_df`.
Proses ini dapat dilakukan menggunakan method `info()` seperti contoh kode berikut.

In [ ]:
customers_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1007 entries, 0 to 1006
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   customer_id    1007 non-null   int64 
 1   customer_name  1007 non-null   object
 2   gender         989 non-null    object
 3   age            1007 non-null   int64 
 4   home_address   1007 non-null   object
 5   zip_code       1007 non-null   int64 
 6   city           1007 non-null   object
 7   state          1007 non-null   object
 8   country        1007 non-null   object
dtypes: int64(3), object(6)
memory usage: 70.9+ KB


Kode `customers_df.info()` digunakan untuk menampilkan **informasi lengkap** tentang data yang ada di dalam DataFrame `customers_df`. Perintah ini akan menunjukkan jumlah baris dan kolom, nama setiap kolom, tipe data pada tiap kolom (misalnya integer, float, object), serta jumlah data yang tidak kosong (**non-null**). Dengan melihat informasi ini, kita bisa memahami struktur data secara cepat dan mengetahui apakah ada data yang hilang atau tipe data yang perlu diperbaiki sebelum melakukan analisis lebih lanjut.


Jika di perhatikan, tidak ada masalah dengan tipe data dari seluruh kolom tersebut. Akan tetapi, terdapat sedikit perbedaan pada jumlah data pada kolom gender. Hal ini menunjukkan adanya **missing values** pada **kolom gender**. Nah, untuk memastikan hal ini, jalankan kode berikut.

In [ ]:
customers_df.isna().sum()

customer_id       0
customer_name     0
gender           18
age               0
home_address      0
zip_code          0
city              0
state             0
country           0
dtype: int64

Kode `customers_df.isna().sum()` digunakan untuk mengecek jumlah **data yang kosong (missing values)** pada setiap kolom di DataFrame `customers_df`. Fungsi `isna()` akan menandai nilai yang hilang sebagai *True*, dan `sum()` akan menghitung berapa banyak *True* tersebut di tiap kolom. Hasilnya adalah daftar jumlah nilai kosong per kolom, sehingga kita bisa mengetahui bagian mana dari data yang perlu dibersihkan sebelum dianalisis.


Terdapat 18 data yang hilang atau missing value pada kolom gender.
Hal ini yang akan tangani pada tahap data cleaning

Masalah selanjutnya yang harus kita periksa ialah **duplikasi data**. dengan menggunakan method `df.duplicated()` Untuk memeriksa hal ini, kita bisa menjalankan kode berikut.

In [ ]:
print("Jumlah duplikasi: ", customers_df.duplicated().sum())

Jumlah duplikasi:  6


Kode `print("Jumlah duplikasi: ", customers_df.duplicated().sum())` digunakan untuk menghitung dan menampilkan jumlah **baris duplikat** dalam DataFrame `customers_df`. Fungsi `duplicated()` akan menandai baris yang isinya sama persis dengan baris lain sebagai *True*, lalu `sum()` menghitung berapa banyak baris yang dianggap duplikat. Hasil akhirnya dicetak ke layar sehingga kita bisa mengetahui apakah ada data ganda yang perlu dibersihkan agar analisis lebih akurat.


Ketika menjalankan kode di atas, akan menemukan terdapat **6 data yang terduplikat**. Pada tahap data cleaning nanti, kita akan menghilangkan semua duplikasi tersebut.

Sekarang kita memeriksa **parameter statistik** dari kolom numerik yang terdapat dalam `customers_df`. Untuk mempermudah pemeriksaan, kita akan menggunakan method` describe()`. Method tersebut akan menampilkan ringkasan parameter statistik `(mean, median, dll.)` dari **kolom numerik** pada **sebuah DataFrame**. Berikut merupakan contoh penggunaannya.

In [ ]:
customers_df.describe()

customer_id          age     zip_code
count  1007.000000  1007.000000  1007.000000
mean    501.726912    50.929494  5012.538232
std     288.673238    30.516299  2885.836112
min       1.000000    20.000000     2.000000
25%     252.500000    34.000000  2403.500000
50%     502.000000    50.000000  5087.000000
75%     751.500000    65.000000  7493.500000
max    1000.000000   700.000000  9998.000000

Kode `customers_df.describe()` digunakan untuk menampilkan **statistik deskriptif** dari kolom-kolom yang berisi data numerik di DataFrame `customers_df`. Perintah ini akan menampilkan informasi seperti nilai minimum, maksimum, rata-rata (mean), median (50%), standar deviasi, serta jumlah data pada setiap kolom numerik. Hasil ini membantu memahami gambaran umum data, seperti sebaran nilai, kecenderungan, dan kemungkinan adanya data yang tidak wajar.



Jika diperhatikan, terdapat **keanehan** pada **nilai maksimum** yang terdapat pada **kolom age**. Ini kemungkinan besar terjadi karena adanya inaccurate value pada kolom tersebut. Masalah ini juga akan kita bersihkan dalam tahap cleaning data.

**Menilai Data orders_df**

Selanjutnya kita akan menilai data pada `orders_df`.
Mulai dengan memeriksa tipe data dari tiap kolom menggunakan method `info()`.

In [ ]:
orders_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   order_id       1000 non-null   int64 
 1   customer_id    1000 non-null   int64 
 2   payment        1000 non-null   int64 
 3   order_date     1000 non-null   object
 4   delivery_date  1000 non-null   object
dtypes: int64(3), object(2)
memory usage: 39.2+ KB


Kode `orders_df.info()` digunakan untuk menampilkan **informasi lengkap** tentang DataFrame `orders_df`. Perintah ini akan menunjukkan jumlah baris dan kolom, nama setiap kolom, tipe data masing-masing kolom (seperti integer, float, atau object), serta jumlah data yang tidak kosong (**non-null**) pada tiap kolom. Dengan informasi ini, kita bisa mengetahui struktur data, mengecek apakah ada data yang hilang, dan memahami jenis data sebelum melakukan analisis lebih lanjut.


Jika perhatikan, jumlah data pada **orders_df** telah **lengkap** atau dengan kata lain **tidak ada missing value** di dalamnya. Akan tetapi, terdapat kesalahan tipe data untuk kolom `order_date & delivery_date`. Kedua kolom tersebut harusnya direpresentasikan sebagai tipe data `datetime`, bukan `object` (ini digunakan untuk tipe data string).

Berikutnya, perlu memeriksa duplikasi dan ringkasan parameter statistik dari kolom numerik pada `orders_df`

In [ ]:
print("Jumlah duplikasi: ",orders_df.duplicated().sum())

Jumlah duplikasi:  0


Kode `print("Jumlah duplikasi: ", orders_df.duplicated().sum())` digunakan untuk mengecek apakah ada baris data yang **terduplikasi** di dalam DataFrame `orders_df`. Fungsi `duplicated()` akan menandai baris yang memiliki isi sama persis dengan baris lain sebagai *True*, kemudian `sum()` menghitung berapa banyak baris duplikat tersebut. Hasil akhirnya ditampilkan melalui `print()`, sehingga kita bisa mengetahui jumlah duplikasi yang perlu dibersihkan agar analisis data lebih akurat.


In [ ]:
orders_df.describe()

order_id  customer_id       payment
count  1000.000000  1000.000000   1000.000000
mean    500.500000   506.640000  33972.936000
std     288.819436   277.115502  14451.609047
min       1.000000     1.000000  10043.000000
25%     250.750000   275.250000  21329.250000
50%     500.500000   515.000000  33697.500000
75%     750.250000   737.250000  46249.000000
max    1000.000000  1000.000000  59910.000000

Kode `orders_df.describe()` digunakan untuk menampilkan **statistik deskriptif** dari kolom-kolom numerik yang ada di DataFrame `orders_df`. Hasilnya mencakup informasi seperti jumlah data (count), nilai rata-rata (mean), standar deviasi (std), nilai minimum (min), nilai maksimum (max), dan nilai persentil (25%, 50%, 75%). Statistik ini membantu memberikan gambaran umum mengenai distribusi dan karakteristik data, sehingga memudahkan dalam analisis lebih lanjut.


Jika diperhatikan, tidak ada keanehan pada hasil tersebut. Ini menunjukkan tidak terdapat duplikasi dan keanehan nilai pada `orders_df`.

**Menilai Data product_df**

Selanjutnya, kita akan menilai data pada `product_df`. Pertama, gunakan method `info() `untuk memastikan tipe data tiap kolom dalam **product_df** telah sesuai.

In [ ]:
products_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1266 entries, 0 to 1265
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   product_id    1266 non-null   int64 
 1   product_type  1266 non-null   object
 2   product_name  1266 non-null   object
 3   size          1266 non-null   object
 4   colour        1266 non-null   object
 5   price         1266 non-null   int64 
 6   quantity      1266 non-null   int64 
 7   description   1266 non-null   object
dtypes: int64(3), object(5)
memory usage: 79.3+ KB


Kode `products_df.info()` digunakan untuk menampilkan **informasi lengkap** mengenai struktur DataFrame `products_df`. Perintah ini menunjukkan jumlah baris dan kolom, nama setiap kolom, tipe data tiap kolom (seperti integer, float, atau object), serta jumlah nilai yang tidak kosong (**non-null**) pada masing-masing kolom. Dengan melihat informasi ini, kita dapat memahami bentuk data, mendeteksi adanya data yang hilang, dan memastikan tipe data sudah sesuai sebelum melakukan analisis lebih lanjut.


Berdasarkan hasil tersebut, dapat disimpulkan bahwa tidak terdapat masalah pada tipe data tiap kolom dalam **product_df**.  Selain itu, jumlah datanya juga telah **lengkap** sehingga **tidak ada missing value** di dalamnya

In [ ]:
print("Jumlah duplikasi: ", products_df.duplicated().sum())

Jumlah duplikasi:  6


Kode `print("Jumlah duplikasi: ", products_df.duplicated().sum())` digunakan untuk mengecek apakah terdapat baris data yang **terduplikasi** di dalam DataFrame `products_df`. Fungsi `duplicated()` akan menandai setiap baris yang memiliki isi sama persis dengan baris lain sebagai *True*, kemudian `sum()` menghitung jumlah baris yang ditandai tersebut. Hasilnya ditampilkan melalui `print()`, sehingga kita bisa mengetahui apakah dataset produk memiliki data ganda yang perlu dibersihkan agar analisis lebih akurat dan tidak bias.


In [ ]:
products_df.describe()

product_id        price     quantity
count  1266.000000  1266.000000  1266.000000
mean    627.926540   105.812006    60.138231
std     363.971586     9.715611    11.682791
min       0.000000    90.000000    40.000000
25%     313.250000    95.250000    50.000000
50%     626.500000   109.000000    60.000000
75%     942.750000   114.000000    70.000000
max    1259.000000   119.000000    80.000000

Kode `products_df.describe()` digunakan untuk menampilkan **statistik deskriptif** dari kolom-kolom numerik yang ada di DataFrame `products_df`. Hasilnya mencakup informasi seperti jumlah data (count), nilai rata-rata (mean), standar deviasi (std), nilai minimum (min), nilai maksimum (max), serta nilai persentil (25%, 50%, 75%). Statistik ini membantu memberikan gambaran awal mengenai karakteristik data produk, seperti kisaran harga atau jumlah stok, sehingga memudahkan proses analisis selanjutnya.


Berdasarkan gambar di atas, dapat dilihat bahwa terdapat **6 data** yang **terduplikasi** pada `product_df`. Pada tahap cleaning data, kita akan menghapus duplikasi tersebut.

**Menilai Data sales_df**
Data terakhir yang harus kita nilai ialah `sales_df`. Sebagai permulaan, gunakan method `info()` untuk memeriksa tipe data dan jumlah data yang ada di dalam **sales_df**.

In [ ]:
sales_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   sales_id        5000 non-null   int64  
 1   order_id        5000 non-null   int64  
 2   product_id      5000 non-null   int64  
 3   price_per_unit  5000 non-null   int64  
 4   quantity        5000 non-null   int64  
 5   total_price     4981 non-null   float64
dtypes: float64(1), int64(5)
memory usage: 234.5 KB


Kode `sales_df.info()` digunakan untuk menampilkan **informasi lengkap** tentang struktur DataFrame `sales_df`. Perintah ini menunjukkan jumlah baris dan kolom, nama setiap kolom, tipe data pada masing-masing kolom (seperti integer, float, atau object), serta jumlah data yang tidak kosong (**non-null**) pada tiap kolom. Dengan melihat informasi ini, kita bisa mengetahui apakah ada data yang hilang, memastikan tipe datanya sudah sesuai, dan memahami struktur dataset sebelum melanjutkan ke tahap analisis lebih lanjut.


Berdasarkan hasil di atas, **tidak ada** masalah pada tipe data tiap kolom dalam `sales_df`. Namun, terdapat **keanehan** pada jumlah data pada kolom `total_price`. Hal ini menunjukkan adanya `missing value` pada kolom tersebut.

In [ ]:
sales_df.isna().sum()

sales_id           0
order_id           0
product_id         0
price_per_unit     0
quantity           0
total_price       19
dtype: int64

Kode `sales_df.isna().sum()` digunakan untuk mengecek jumlah **data yang kosong (missing values)** di setiap kolom dalam DataFrame `sales_df`. Fungsi `isna()` akan menandai nilai yang kosong sebagai *True*, lalu `sum()` menghitung berapa banyak nilai kosong tersebut per kolom. Hasilnya akan menunjukkan kolom mana saja yang memiliki data hilang sehingga kita dapat mengetahui bagian data yang perlu dibersihkan sebelum melakukan analisis lebih lanjut.


Kode di atas akan menunjukkan **jumlah missing value** dari setiap kolom dalam `sales_df`. Berikut merupakan hasil yang kita peroleh.

Berdasarkan hasil di atas, dapat disimpulkan bahwa terdapat **19 missing value** pada kolom `total_price`. Hal ini akan kita bersihkan pada tahap cleaning data.

selanjutnya ialah memeriksa duplikasi dan ringkasan parameter statistik dari `sales_df`

In [ ]:
print("Jumlah duplikasi: ", sales_df.duplicated().sum())

Jumlah duplikasi:  0


Kode `print("Jumlah duplikasi: ", sales_df.duplicated().sum())` digunakan untuk menghitung dan menampilkan jumlah **baris duplikat** dalam DataFrame `sales_df`. Fungsi `duplicated()` akan menandai baris yang isinya sama persis dengan baris lain sebagai *True*, kemudian `sum()` menghitung berapa banyak baris duplikat tersebut. Hasil perhitungan ini ditampilkan melalui `print()`, sehingga kita dapat mengetahui apakah terdapat data ganda yang perlu dibersihkan agar analisis menjadi lebih akurat dan tidak bias.


In [ ]:
sales_df.describe()

sales_id     order_id   product_id  price_per_unit    quantity  \
count  5000.000000  5000.000000  5000.000000     5000.000000  5000.00000   
mean   2499.500000   503.038200   634.053200      103.501600     1.99240   
std    1443.520003   285.964418   363.255794        9.195004     0.80751   
min       0.000000     1.000000     1.000000       90.000000     1.00000   
25%    1249.750000   258.000000   323.000000       95.000000     1.00000   
50%    2499.500000   504.500000   635.000000      102.000000     2.00000   
75%    3749.250000   749.000000   951.000000      112.000000     3.00000   
max    4999.000000   999.000000  1259.000000      119.000000     3.00000   

       total_price  
count  4981.000000  
mean    206.307368  
std      86.352449  
min      90.000000  
25%     112.000000  
50%     204.000000  
75%     285.000000  
max     357.000000

Kode `sales_df.describe()` digunakan untuk menampilkan **statistik deskriptif** dari kolom-kolom numerik di DataFrame `sales_df`. Hasil yang ditampilkan meliputi jumlah data (count), nilai rata-rata (mean), standar deviasi (std), nilai minimum (min), nilai maksimum (max), serta nilai persentil (25%, 50%, dan 75%). Statistik ini membantu memberikan gambaran umum mengenai karakteristik data penjualan, seperti sebaran jumlah transaksi atau total nilai penjualan, sehingga memudahkan analisis lebih lanjut.


Hasil di atas menunjukkan bahwa tidak ada duplikasi pada` sales_df`. Selain itu, ia juga menunjukkan tidak terdapat keanehan dalam ringkasan parameter statistik dari sales_df.

sampai tahap ini, kita telah berhasil mengidentifikasi berbagai masalah pada data yang telah kita kumpulkan. Berikut merupakan rangkumannya.

| Datasheet | Tipe data | Missing Value | Duplicated |Inaccurate value |
| :----------- |:--------------:| -------------:| -------------:|-------------:|
| Customers    | -              | Terdapat 18 missing values pada kolom gender.            | Terdapat 6 data yang duplikat. | Terdapat inaccurate value pada kolom age.|
| Orders     | Terdapat kesalahan tipe data untuk kolom order_date & delivery_date.           | -       | - | -  |
| Products     | -           | -       |
Terdapat 6 data yang duplikat. | - |
| Sales      | -           | Terdapat 19 missing value pada kolom total_price.         |- | - |

**Cleaning Data**

**Membersihkan Data customers_df**
Berdasarkan hasil proses assessing data, diketahui bahwa terdapat tiga masalah yang dijumpai dalam customer_df, yaitu duplicate data, missing value, dan inaccurate value.

Menghilangkan duplicate data

 untuk melakukan hal ini, kita dapat memanfaatkan method `drop_duplicates()`. Berikut merupakan kode untuk menghapus duplikasi pada `customer_df`.

In [ ]:
customers_df.drop_duplicates(inplace=True)

Kode `customers_df.drop_duplicates(inplace=True)` digunakan untuk **menghapus baris data yang duplikat** dari DataFrame `customers_df`. Fungsi `drop_duplicates()` akan mencari baris yang memiliki isi sama persis dengan baris lain dan menghapusnya. Penggunaan `inplace=True` membuat perubahan dilakukan langsung pada DataFrame tanpa perlu membuat salinan baru. Dengan cara ini, data menjadi lebih bersih dan tidak ada pengulangan yang bisa membuat hasil analisis menjadi bias.


Setelah menjalankan kode di atas, periksa kembali apakah masih terdapat duplikasi pada data tersebut dengan menjalankan kode berikut.

In [ ]:
print("Jumlah duplikasi: ", customers_df.duplicated().sum())

Jumlah duplikasi:  0


Kode `print("Jumlah duplikasi: ", customers_df.duplicated().sum())` digunakan untuk mengecek kembali apakah masih ada **baris duplikat** dalam DataFrame `customers_df` setelah proses pembersihan. Fungsi `duplicated()` menandai baris yang duplikat sebagai *True*, lalu `sum()` menghitung jumlahnya. Hasilnya ditampilkan melalui `print()`. Jika hasilnya **0**, berarti semua data duplikat telah berhasil dihapus dan DataFrame sudah bersih dari pengulangan.


Jika proses penghapusan duplikasi berjalan lancar, kode di atas akan menghasilkan keluaran yang menunjukkan tidak adanya duplikasi pada `customers_df`.

**Menangani missing value**

Masalah berikutnya yang harus kita tangani ialah missing value pada kolom gender. Nah, secara umum terdapat tiga metode untuk mengatasi missing value yaitu dropping, imputation, dan interpolation. Untuk menentukan metode mana yang akan digunakan, kita perlu melihat data yang mengandung missing value tersebut menggunakan teknik filtering seperti berikut.

In [ ]:
customers_df[customers_df.gender.isna()]

customer_id customer_name gender  age                     home_address  \
38            39      fulan 39    NaN   80  7440 Cameron Estate DrSuite 628   
167          168     fulan 168    NaN   27         2781 Berge MallSuite 452   
322          322     fulan 322    NaN   30        593 Becker CircleApt. 333   
393          393     fulan 393    NaN   34          5158 Levi HillSuite 531   
442          442     fulan 442    NaN   26           5157 Feil RoadApt. 633   
722          720     fulan 720    NaN   40         31 Jordan ParadeApt. 400   
745          743     fulan 743    NaN   57   09 Christopher StreetSuite 967   
773          771     fulan 771    NaN   74     7367 Wright JunctionApt. 773   
798          795     fulan 795    NaN   49          487 Summer MewsApt. 874   
801          798     fulan 798    NaN   56           27 Aiden KnollApt. 875   
825          822     fulan 822    NaN   59        41 Jenkins KnollSuite 438   
859          855     fulan 855    NaN   55       603 O'keefe KnollSuite 782   
863          859     fulan 859    NaN   38            32 Isla GroveApt. 078   
914          909     fulan 909    NaN   62    976 Murray Station StApt. 036   
934          929     fulan 929    NaN   68           394 Lily HillSuite 153   
948          943     fulan 943    NaN   64       3117 Heller PlaceSuite 149   
952          946     fulan 946    NaN   24      8227 Nicholas HillSuite 150   
994          988     fulan 988    NaN   35   1130 Turner Estate DrSuite 925   

     zip_code                   city                         state    country  
38       4622  North Victoriachester            Northern Territory  Australia  
167      1975         North Leoburgh             Western Australia  Australia  
322      1640             Jacobiview             Western Australia  Australia  
393      1474             Johnsburgh                    Queensland  Australia  
442      7249             Port Chloe               New South Wales  Australia  
722      1380             West Henry               South Australia  Australia  
745      6226         Lake Lukemouth             Western Australia  Australia  
773      8882               Kuhntown                      Victoria  Australia  
798      1712            East Hayden  Australian Capital Territory  Australia  
801      6531               Port Sam  Australian Capital Territory  Australia  
825      2588        Lake Andrewport               South Australia  Australia  
859      8822        Port Dylanmouth                      Tasmania  Australia  
863      7711            Rosechester               New South Wales  Australia  
914      3227               Langfort                      Tasmania  Australia  
934      2353             Beahanfurt            Northern Territory  Australia  
948       822           North Elijah               South Australia  Australia  
952       115           South Jasper                    Queensland  Australia  
994      9386              New Harry             Western Australia  Australia

Kode `customers_df[customers_df.gender.isna()]` digunakan untuk **menampilkan baris-baris yang memiliki nilai kosong (NaN)** pada kolom **gender** di DataFrame `customers_df`. Bagian `customers_df.gender.isna()` akan menghasilkan nilai *True* untuk baris yang kolom gender-nya kosong, lalu DataFrame di luar kurung `customers_df[...]` akan menampilkan hanya baris-baris tersebut. Dengan perintah ini, kita dapat melihat pelanggan mana saja yang belum memiliki data gender, sehingga memudahkan proses pengecekan atau pengisian data yang hilang.


Kode di atas hanya akan menampilkan baris data yang memenuhi kondisi `customers_df.gender.isna()` atau dengan kata lain ia akan menampilkan baris data yang mengandung missing value pada kolom gender

Berdasarkan gambar di atas, dapat dilihat bahwa baris data tersebut masih mengandung banyak informasi penting sehingga sayang jika langsung dibuang. Oleh karena itu, pada kasus ini, kita akan menggunakan **metode imputation** untuk menangani **missing value**.

Gunakanlah method `value_counts()`untuk mengidentifikasi nilai yang dominan.

In [ ]:
customers_df.gender.value_counts()

gender
Prefer not to say    725
Male                 143
Female               115
Name: count, dtype: int64

Kode `customers_df.gender.value_counts()` digunakan untuk menghitung **jumlah kemunculan setiap kategori gender** yang ada di dalam kolom **gender** pada DataFrame `customers_df`. Hasilnya akan menampilkan berapa banyak pelanggan yang memiliki gender tertentu, misalnya berapa banyak yang “Male” dan berapa yang “Female”. Perintah ini berguna untuk melihat distribusi gender secara cepat dan memahami komposisi data pelanggan berdasarkan jenis kelamin.


Berdasarkan hasil di atas, dapat diketahui bahwa nilai yang paling dominan dalam kolom gender ialah **“Prefer not to say”.** Nilai inilah yang selanjutnya akan kita gunakan sebagai pengganti missing value. Proses penggantian ini dapat dilakukan menggunakan method `fillna()`seperti contoh berikut.

Untuk memastikan proses di atas berjalan dengan semestinya, kita bisa menjalankan kembali kode untuk mengidentifikasi missing value seperti berikut.

In [ ]:
customers_df.isna().sum()

customer_id       0
customer_name     0
gender           18
age               0
home_address      0
zip_code          0
city              0
state             0
country           0
dtype: int64

Kode `customers_df.isna().sum()` digunakan untuk menghitung jumlah **nilai kosong (missing values)** pada setiap kolom dalam DataFrame `customers_df`. Fungsi `isna()` akan menandai sel yang kosong sebagai *True*, kemudian `sum()` menjumlahkan berapa banyak nilai kosong tersebut di setiap kolom. Hasilnya menunjukkan kolom mana yang masih memiliki data hilang dan perlu dibersihkan sebelum analisis dilakukan.


**Menangani inaccurate value**

sekarang kita akan mengatasi masalah inaccurate value pada kolom age. Sebagai awal, kita perlu melihat data baris data yang mengandung inaccurate value tersebut (baris dengan nilai age maksimum). Hal ini dilakukan menggunakan teknik filter seperti contoh kode berikut.

In [ ]:
customers_df[customers_df.age == customers_df.age.max()]

customer_id customer_name             gender  age  \
967          961     fulan 961  Prefer not to say  700   

                   home_address  zip_code        city            state  \
967  29 Farrell ParadeSuite 818      6528  New Joseph  South Australia   

       country  
967  Australia

Kode `customers_df[customers_df.age == customers_df.age.max()]` digunakan untuk menampilkan **baris data pelanggan yang memiliki umur paling tua** di dalam DataFrame `customers_df`. Bagian `customers_df.age.max()` mencari nilai umur tertinggi, lalu ekspresi `customers_df.age == customers_df.age.max()` menghasilkan *True* untuk baris yang umur-nya sama dengan nilai maksimum tersebut. Hasilnya adalah tabel yang berisi satu atau lebih pelanggan dengan usia tertua dalam dataset.


Kode di atas akan menampilkan baris data yang memiliki nilai age maksimum.

Berdasarkan data tersebut, kita bisa berasumsi bahwa **inaccurate value** tersebut terjadi karena **human error** sehingga kelebihan memasukkan nilai nol. Oleh karena itu, gantilah dengan **nilai 70** . Proses ini dilakukan dengan memanfaatkan **method** `replace()`seperti contoh berikut.

In [ ]:
customers_df.age.replace(customers_df.age.max(), 70, inplace=True)

/tmp/ipython-input-4147959128.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  customers_df.age.replace(customers_df.age.max(), 70, inplace=True)


Kode `customers_df.age.replace(customers_df.age.max(), 70, inplace=True)` digunakan untuk **mengganti nilai umur tertentu di dalam kolom `age`** pada DataFrame `customers_df`. Bagian `customers_df.age.max()` mencari nilai umur **tertinggi** dalam data, lalu fungsi `replace()` mengganti nilai umur tertinggi tersebut menjadi **70**. Penggunaan `inplace=True` membuat perubahan langsung diterapkan pada DataFrame tanpa membuat salinan baru. Dengan kata lain, kode ini dipakai untuk memperbaiki atau menyesuaikan data umur yang dianggap tidak wajar atau terlalu ekstrem.


In [ ]:
customers_df[customers_df.age == customers_df.age.max()]

customer_id customer_name             gender  age  \
215          216     fulan 216  Prefer not to say  500   

               home_address  zip_code       city               state  \
215  038 Haley MewsApt. 810      3991  Bayertown  Northern Territory   

       country  
215  Australia

Kode `customers_df[customers_df.age == customers_df.age.max()]` digunakan untuk menampilkan **baris pelanggan dengan umur tertinggi** setelah proses penggantian nilai umur sebelumnya. Ekspresi `customers_df.age.max()` mencari nilai umur terbesar yang masih ada di kolom `age`, lalu DataFrame akan menampilkan baris yang memenuhi kondisi tersebut. Perintah ini biasanya digunakan untuk memastikan bahwa nilai umur ekstrem yang lama benar-benar sudah diganti dan data sudah sesuai dengan yang diinginkan.


Pastikan lagi bahwa tidak ada data yang inaccurate pada kolom age

In [ ]:
customers_df.describe()

customer_id          age     zip_code
count  1001.000000  1001.000000  1001.000000
mean    500.942058    50.323676  5000.693307
std     289.013599    22.665946  2886.084454
min       1.000000    20.000000     2.000000
25%     251.000000    34.000000  2398.000000
50%     501.000000    50.000000  5079.000000
75%     751.000000    65.000000  7454.000000
max    1000.000000   500.000000  9998.000000

Kode `customers_df.describe()` digunakan untuk menampilkan **statistik deskriptif** dari kolom-kolom numerik di DataFrame `customers_df`. Hasilnya menunjukkan informasi seperti jumlah data (count), nilai rata-rata (mean), standar deviasi (std), nilai minimum (min), nilai maksimum (max), serta persentil (25%, 50%, 75%). Dengan melihat output ini, kita bisa memahami gambaran umum data pelanggan, seperti sebaran umur atau pola nilai numerik lainnya, sehingga analisis selanjutnya bisa dilakukan dengan lebih mudah dan tepat.


Berdasarkan hasil tersebut dapat dilihat bahwa kolom **age** memiliki **nilai maksimum** yang cukup masuk akal. Selain itu, jika Ada perhatikan, nilai **mean dan standard deviation** ikut berubah setelah kita menangani inaccurate value tersebut.

**Membersihkan Data orders_df**
Sekarang kita telah menyelesaikan semua permasalahan yang ada pada `customers_df`. Selanjutnya, kita akan mengatasi permasalahan pada `orders_df`. Berdasarkan proses assessing data sebelumnya, diketahui bahwa terdapat kesalahan tipe data untuk kolom `order_date & delivery_date`.

Untuk mengatasi masalah ini, kita akan mengganti tipe data pada kolom order_date & delivery_date menjadi datetime. Proses ini dapat dilakukan menggunakan function to_datetime() yang disediakan oleh library pandas

In [ ]:
datetime_columns = ["order_date", "delivery_date"]

for column in datetime_columns:
  orders_df[column] = pd.to_datetime(orders_df[column])

Kode tersebut digunakan untuk **mengubah kolom tanggal** di DataFrame `orders_df` menjadi tipe data **datetime** agar lebih mudah diproses. Pertama, variabel `datetime_columns` berisi daftar nama kolom yang ingin diubah, yaitu `"order_date"` dan `"delivery_date"`. Lalu, perulangan `for` digunakan untuk mengambil setiap nama kolom dalam daftar tersebut dan menjalankan `pd.to_datetime()` untuk mengubah isi kolom yang awalnya berupa teks menjadi format tanggal yang sebenarnya. Dengan cara ini, data tanggal dapat digunakan untuk perhitungan waktu, pengurutan tanggal, atau analisis lainnya dengan lebih akurat.


Kode di atas akan mengubah tipe data pada kolom `order_date & delivery_date` menjadi `datetime`. Untuk memastikan hal ini berjalan sesuai harapan, periksa kembali tipe data tersebut menggunakan method `info()`.

In [ ]:
orders_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype         
---  ------         --------------  -----         
 0   order_id       1000 non-null   int64         
 1   customer_id    1000 non-null   int64         
 2   payment        1000 non-null   int64         
 3   order_date     1000 non-null   datetime64[ns]
 4   delivery_date  1000 non-null   datetime64[ns]
dtypes: datetime64[ns](2), int64(3)
memory usage: 39.2 KB


Kode `orders_df.info()` digunakan untuk menampilkan **informasi lengkap** tentang struktur DataFrame `orders_df` setelah kolom tanggal diubah menjadi tipe datetime. Perintah ini menampilkan jumlah baris dan kolom, nama setiap kolom, tipe data masing-masing kolom (termasuk apakah sudah menjadi datetime), serta jumlah data yang tidak kosong (**non-null**) pada tiap kolom. Dengan melihat output ini, kita dapat memastikan bahwa kolom `order_date` dan `delivery_date` sudah berhasil dikonversi ke format tanggal dan data siap digunakan untuk analisis waktu.


Jika semua tahapan berjalan sesuai harapanm, Maka tipe data kedua kolom sudah berganti menjadi **datetime**

Data berikutnya yang akan bersihkan ialah **product_df**. Sesuai hasil assessing data sebelumnya, kita mengetahui bahwa terdapat `6 data` yang **terduplikasi** pada **product_df.** Untuk mengatasi hal ini, kita perlu membuang data yang sama tersebut menggunakan **method** `drop_duplicates()` seperti contoh berikut.

In [ ]:
products_df.drop_duplicates(inplace=True)

Kode `products_df.drop_duplicates(inplace=True)` digunakan untuk **menghapus baris data yang duplikat** dari DataFrame `products_df`. Fungsi `drop_duplicates()` akan mencari baris yang memiliki isi sama persis dengan baris lain dan menghapusnya. Karena menggunakan `inplace=True`, perubahan ini dilakukan langsung pada DataFrame tanpa membuat salinan baru. Dengan perintah ini, dataset produk menjadi lebih bersih dan bebas dari data ganda yang bisa mempengaruhi hasil analisis.


Kode di atas akan menghapus semua data yang duplikat. Untuk memastikan kode tersebut berjalan sesuai harapan, jalankanlah kode berikut.

In [ ]:
print("Jumlah duplikasi: ", products_df.duplicated().sum())

Jumlah duplikasi:  0


Kode `print("Jumlah duplikasi: ", products_df.duplicated().sum())` digunakan untuk mengecek kembali apakah masih ada **baris yang duplikat** di DataFrame `products_df` setelah proses penghapusan duplikasi dilakukan. Fungsi `duplicated()` akan menandai baris yang isinya sama dengan baris lain sebagai *True*, kemudian `sum()` menghitung jumlah baris duplikat tersebut. Hasilnya dicetak ke layar menggunakan `print()`. Jika angka yang ditampilkan adalah **0**, berarti semua duplikasi sudah berhasil dihapus dan data produk sudah bersih.


Jika proses penghapusan data yang duplikat berjalan dengan lancar, kode di atas akan menghasilkan keluaran seperti berikut **“Jumlah duplikasi:  0”**.

**Membersihkan Data sales_df**

Data selanjutnya yang perlu bersihkan ialah `sales_df`. Berdasarkan hasil penilain data sebelumnya, diketahui bahwa terdapat **19 missing value** pada kolom `total_price`. Untuk mengetahui proses penanganan missing value yang paling sesuai, kita perlu melihat terlebih dahulu baris data yang mengandung missing value tersebut.

In [ ]:
sales_df[sales_df.total_price.isna()]

sales_id  order_id  product_id  price_per_unit  quantity  total_price
9            9         2        1196             105         1          NaN
121        121        27        1027              90         3          NaN
278        278        63         360              94         2          NaN
421        421        95        1091             115         1          NaN
489        489       108        1193             105         3          NaN
539        539       117         405             119         2          NaN
636        636       134         653              93         3          NaN
687        687       145        1138             102         1          NaN
854        854       177          64             104         1          NaN
1079      1079       222         908              94         3          NaN
1193      1193       248        1121             102         2          NaN
1313      1313       272         826             117         1          NaN
1548      1548       316         103             118         3          NaN
1688      1688       345         428             107         1          NaN
1775      1775       359         694             113         2          NaN
1902      1902       381        1218             105         3          NaN
2025      2025       408         611             112         3          NaN
2164      2164       436         583             100         3          NaN
2347      2347       476         696             113         2          NaN

Kode `sales_df[sales_df.total_price.isna()]` digunakan untuk **menampilkan baris-baris data yang memiliki nilai kosong (NaN)** pada kolom **`total_price`** dalam DataFrame `sales_df`. Bagian `sales_df.total_price.isna()` akan menghasilkan nilai *True* untuk setiap baris yang kolom `total_price`-nya kosong, kemudian DataFrame di luar kurung `sales_df[...]` akan menampilkan hanya baris-baris tersebut. Dengan perintah ini, kita bisa melihat transaksi mana saja yang tidak memiliki nilai total harga, sehingga memudahkan proses pengecekan atau perbaikan data sebelum analisis dilanjutkan.


Kode di atas akan menampilkan semua baris data yang memiliki **missing value** pada kolom `total_price` seperti pada gambar di atas.

Berdasarkan tampilan data tersebut, kita menemukan bahwa nilai `total_price` merupakan hasil **perkalian** antara `price_per_unit dan quantity`.

Kita dapat menggunakan pola ini untuk menangani missing value pada kolom `total_price`. Berikut merupakan contoh penerapan kode untuk melakukannya.

In [ ]:
sales_df["total_price"] = sales_df["price_per_unit"] * sales_df["quantity"]

Kode `sales_df["total_price"] = sales_df["price_per_unit"] * sales_df["quantity"]` digunakan untuk **menghitung total harga** setiap transaksi dalam DataFrame `sales_df`. Caranya adalah dengan mengalikan nilai harga per unit (`price_per_unit`) dengan jumlah barang yang dibeli (`quantity`). Hasil perkalian tersebut kemudian disimpan ke dalam kolom baru bernama **`total_price`**. Dengan adanya kolom ini, analisis penjualan seperti total pendapatan atau perbandingan nilai transaksi menjadi lebih mudah dilakukan.


Kode di atas akan **mengatasi** seluruh `missing value` serta memastikan nilai pada kolom `total_price` telah sesuai. Untuk memastikan hal ini, Anda dapat memeriksa kembali **jumlah missing value** pada `sales_df `menggunakan kode berikut.

In [ ]:
sales_df.isna().sum()

sales_id          0
order_id          0
product_id        0
price_per_unit    0
quantity          0
total_price       0
dtype: int64

Kode `sales_df.isna().sum()` digunakan untuk menghitung jumlah **nilai kosong (missing values)** pada setiap kolom di DataFrame `sales_df`. Fungsi `isna()` akan menandai sel yang kosong sebagai *True*, lalu `sum()` menjumlahkan berapa banyak nilai kosong tersebut di tiap kolom. Dengan perintah ini, kita bisa mengetahui apakah masih ada data yang hilang setelah memperbaiki atau menambahkan nilai pada kolom tertentu, sehingga memastikan dataset sudah bersih sebelum analisis lanjutan.


Jika proses sebelumnya berjalan lancar, Anda akan menemukan hasil seperti gambar di atas.

Tahapan di atas adalah Proses data wrangling untuk menyiapkan data sebelum dianalisis

**Exploratory Data Analysis**

Setelah memahami semua teori tentang proses **EDA**, kini saatnya kita menerapkannya dalam sebuah proyek analisis data sederhana.

**Menentukan Pertanyaan Bisnis**

Seperti yang telah kita bahas sebelumnya, untuk menentukan sebuah pertanyaan, kita perlu memahami permasalahan bisnis yang dihadapi terlebih dahulu. Nah, pada proyek ini, kita dihadapkan dengan sebuah contoh kasus dari perusahaan online fashion bernama Fashion Collection (FCO).

Sebagai perusahaan yang bergerak di bidang online fashion, Fashion Collection (FCO) perlu mengevaluasi performa penjualan (sales) dan memahami item fashion yang paling banyak dibeli. Selain itu, ia juga perlu lebih memahami pelanggannya (customer) sehingga dapat membuat sebuah strategi campaign yang lebih efisien.

Berdasarkan beberapa masalah tersebut, kita dapat mendefinisikan beberapa pertanyaan bisnis seperti berikut.


1.   Bagaimana performa penjualan dan revenue perusahaan dalam beberapa bulan terakhir?
2. Produk apa yang paling banyak dan paling sedikit terjual?
3. Bagaimana demografi pelanggan yang kita miliki?
4. Kapan terakhir pelanggan melakukan transaksi?
5. Seberapa sering seorang pelanggan melakukan pembelian dalam beberapa bulan terakhir?
6. Berapa banyak uang yang dihabiskan pelanggan dalam beberapa bulan terakhir?.


 keenam pertanyaan bisnis yang harus kita jawab melalui proses analisis data

**Melakukan Eksplorasi Data**

**Eksplorasi Data customers_df**

Pertama, kita akan mengeksplorasi data customers_df terlebih dahulu. Seperti yang kita ketahui, dataset ini memuat berbagai informasi terkait customer, seperti customer_id, customer_name, gender, age, home_address, zip_code, city, state, dan country.

melihat rangkuman parameter statistik dari data customers_df menggunakan method `describe()`

In [ ]:
customers_df.describe(include="all")

customer_id customer_name             gender          age  \
count   1001.000000          1001                983  1001.000000   
unique          NaN          1000                  3          NaN   
top             NaN     fulan 943  Prefer not to say          NaN   
freq            NaN             2                725          NaN   
mean     500.942058           NaN                NaN    50.323676   
std      289.013599           NaN                NaN    22.665946   
min        1.000000           NaN                NaN    20.000000   
25%      251.000000           NaN                NaN    34.000000   
50%      501.000000           NaN                NaN    50.000000   
75%      751.000000           NaN                NaN    65.000000   
max     1000.000000           NaN                NaN   500.000000   

                      home_address     zip_code        city            state  \
count                         1001  1001.000000        1001             1001   
unique                        1000          NaN         961                8   
top     3117 Heller PlaceSuite 149          NaN  East Aidan  South Australia   
freq                             2          NaN           3              140   
mean                           NaN  5000.693307         NaN              NaN   
std                            NaN  2886.084454         NaN              NaN   
min                            NaN     2.000000         NaN              NaN   
25%                            NaN  2398.000000         NaN              NaN   
50%                            NaN  5079.000000         NaN              NaN   
75%                            NaN  7454.000000         NaN              NaN   
max                            NaN  9998.000000         NaN              NaN   

          country  
count        1001  
unique          1  
top     Australia  
freq         1001  
mean          NaN  
std           NaN  
min           NaN  
25%           NaN  
50%           NaN  
75%           NaN  
max           NaN

Kode `customers_df.describe(include="all")` digunakan untuk menampilkan **statistik deskriptif lengkap** dari seluruh kolom dalam DataFrame `customers_df`, baik kolom numerik maupun kolom kategorikal. Untuk kolom numerik, akan ditampilkan statistik seperti mean, min, max, dan persentil. Sementara untuk kolom kategorikal, akan ditampilkan informasi seperti jumlah data unik, nilai yang paling sering muncul (top), dan frekuensinya (freq). Dengan perintah ini, kita mendapatkan gambaran keseluruhan struktur dan karakteristik data pelanggan secara lebih lengkap dibandingkan `describe()` biasa.


Berdasarkan rangkuman parameter statistik di atas, kita akan memperoleh informasi jumlah pelanggan sebanyak 1001 orang yang berumur di kisaran antara 20 hingga 80 tahun dengan rata-rata umur sebesar 49.87 tahun dengan standar deviasinya sebesar 17.64 tahun. Informasi ini tentunya dapat memberikan gambaran bahwa segmentasi pelanggan yang kita miliki cukup luas mulai dari remaja hingga lanjut usia.  

Sekarang coba kita lihat demografi pelanggan berdasarkan jenis kelamin (gender). Untuk melakukan ini, kita akan menggunakan method groupby() yang diikuti dengan method agg(). Berikut contoh kode untuk melakukannya.

In [ ]:
customers_df.groupby(by="gender").agg({
    "customer_id": "nunique",
    "age": ["max", "min", "mean", "std"]
})

customer_id  age                          
                      nunique  max min       mean        std
gender                                                      
Female                    115   79  20  49.147826  16.646607
Male                      143   80  20  51.230769  18.462635
Prefer not to say         725  500  20  50.369655  24.320004

Kode tersebut digunakan untuk **menganalisis data pelanggan berdasarkan gender** dengan cara mengelompokkan data dan menghitung beberapa statistik penting. Fungsi `groupby(by="gender")` membagi data ke dalam kelompok laki-laki dan perempuan. Setelah itu, `agg()` digunakan untuk menghitung beberapa nilai statistik pada setiap kelompok. Pada kolom `customer_id`, digunakan `"nunique"` untuk menghitung jumlah pelanggan unik pada tiap gender. Pada kolom `age`, dihitung nilai usia **maksimum (max)**, **minimum (min)**, **rata-rata (mean)**, dan **standar deviasi (std)**. Hasil akhirnya adalah tabel ringkas yang menunjukkan perbandingan karakteristik pelanggan antara masing-masing gender.


Kode di atas akan menghasilkan sebuah pivot table. Ia memuat informasi jumlah pelanggan (nunique dari customer_id) serta parameter umur yang dikelompokkan berdasarkan jenis kelamin.


Berdasarkan pivot table di atas, dapat diketahui bahwa pelanggan yang kita miliki didominasi oleh jenis kelamin prefer not to say. Di lain sisi, distribusi umur mereka ternyata cukup mirip yaitu berkisar antara 20 hingga 80 tahun.

Selanjutnya, kita coba melihat persebaran jumlah pelanggan berdasarkan kota (city) dan negara bagian (state). Untuk melakukannya kita juga akan menggunakan method groupby(). Selain itu, agar hasilnya lebih mudah untuk dilihat, kita akan mengurutkan nilainya menggunakan method sort_values() secara descending.

In [ ]:
customers_df.groupby(by="city").customer_id.nunique().sort_values(ascending=False)

city
East Sophia     3
New Ava         3
East Aidan      3
Lake Sienna     2
Jademouth       2
               ..
Justinport      1
Kaiberg         1
Kaifort         1
Kaihaven        1
Johnsonhaven    1
Name: customer_id, Length: 961, dtype: int64

Kode tersebut digunakan untuk **menghitung jumlah pelanggan unik di setiap kota** dan menampilkan hasilnya dari yang terbanyak hingga tersedikit. Pertama, `customers_df.groupby(by="city")` mengelompokkan data berdasarkan nama kota. Lalu, `customer_id.nunique()` menghitung jumlah pelanggan unik di tiap kota tersebut. Terakhir, `sort_values(ascending=False)` mengurutkan hasilnya dari nilai terbesar ke terkecil. Dengan perintah ini, kita dapat mengetahui kota mana yang memiliki jumlah pelanggan paling banyak dan paling sedikit.



In [ ]:
customers_df.groupby(by="state").customer_id.nunique().sort_values(ascending=False)

state
South Australia                 139
Queensland                      134
New South Wales                 132
Northern Territory              125
Western Australia               124
Australian Capital Territory    121
Victoria                        121
Tasmania                        104
Name: customer_id, dtype: int64

Kode tersebut digunakan untuk **menghitung jumlah pelanggan unik berdasarkan provinsi (state)** dan menampilkannya dari yang paling banyak hingga paling sedikit. Pertama, `customers_df.groupby(by="state")` mengelompokkan data pelanggan berdasarkan kolom **state**. Kemudian, `customer_id.nunique()` menghitung jumlah pelanggan unik pada setiap provinsi tersebut. Setelah itu, `sort_values(ascending=False)` mengurutkan hasilnya dari angka yang terbesar ke yang terkecil. Dengan perintah ini, kita bisa melihat provinsi mana yang memiliki pelanggan terbanyak dan paling sedikit.


Berdasarkan hasil di atas, dapat dilihat bahwa persebaran pelanggan kita cukup merata pada setiap kota dan negara bagian. Pelanggan kita paling banyak berada di kota East Aidan, East Sophia, dan New Ava dengan jumlah masing-masing tiga pelanggan. Selain itu, pelanggan kita paling banyak berasal dari negara bagian South Australia.

Oke, sekarang kita telah memiliki cukup banyak informasi terkait data customers_df. Selanjutnya kita akan melakukan eksplorasi terhadap data orders_df

**Eksplorasi Data orders_df**

Data kedua yang akan kita eksplor adalah orders_df. Ia mengandung berbagai informasi terkait sebuah order yang terdiri dari order_id, customer_id, order_date, dan delivery_date

Berdasarkan informasi tersebut, kita bisa membuat sebuah kolom baru untuk memuat waktu pengiriman tiap order. Untuk melakukannya, kita perlu menghitung selisih antar delivery_date dan order_date serta menyimpannya sebagai delivery_time. Selanjutnya, kita akan menggunakan method apply() untuk melakukan sebuah operasi terhadap setiap elemen dalam sebuah kolom DataFrame atau Series (bentuk satu dimensi dari DataFrame).

Operasi yang akan kita lakukan ialah menghitung jumlah detik dari delivery_time menggunakan method total_seconds().  selanjutnya diubah ke dalam satuan hari (dibagi 86400) dan diambil bilangan bulatnya

In [ ]:
delivery_time = orders_df["delivery_date"] - orders_df["order_date"]
delivery_time = delivery_time.apply(lambda x: x.total_seconds())
orders_df["delivery_time"] = round(delivery_time/86400)

Kode tersebut digunakan untuk **menghitung lama pengiriman** setiap pesanan dan menyimpannya ke dalam kolom baru. Pada baris pertama, `delivery_time = orders_df["delivery_date"] - orders_df["order_date"]`, program menghitung selisih antara tanggal pengiriman dan tanggal pemesanan, menghasilkan nilai berupa *timedelta*. Baris kedua, `delivery_time = delivery_time.apply(lambda x: x.total_seconds())`, mengubah selisih waktu tersebut menjadi **detik** agar lebih mudah dihitung. Selanjutnya, `orders_df["delivery_time"] = round(delivery_time/86400)` mengonversi detik menjadi **hari** dengan membagi 86.400 (jumlah detik dalam satu hari), kemudian membulatkannya sebelum disimpan ke kolom baru bernama `delivery_time`. Dengan demikian, setiap pesanan kini memiliki informasi berapa hari waktu yang dibutuhkan untuk pengiriman.


kode di atas, akan menemukan kolom baru pada DataFrame orders_df

In [ ]:
orders_df.describe(include="all")

order_id  customer_id       payment                  order_date  \
count  1000.000000  1000.000000   1000.000000                        1000   
mean    500.500000   506.640000  33972.936000  2021-05-27 18:38:52.800000   
min       1.000000     1.000000  10043.000000         2021-01-01 00:00:00   
25%     250.750000   275.250000  21329.250000         2021-03-13 18:00:00   
50%     500.500000   515.000000  33697.500000         2021-05-27 12:00:00   
75%     750.250000   737.250000  46249.000000         2021-08-12 06:00:00   
max    1000.000000  1000.000000  59910.000000         2021-10-24 00:00:00   
std     288.819436   277.115502  14451.609047                         NaN   

             delivery_date  delivery_time  
count                 1000    1000.000000  
mean   2021-06-10 20:31:12      14.078000  
min    2021-01-03 00:00:00       1.000000  
25%    2021-03-28 00:00:00       8.000000  
50%    2021-06-11 12:00:00      14.000000  
75%    2021-08-24 06:00:00      21.000000  
max    2021-11-20 00:00:00      27.000000  
std                    NaN       7.707225

Kode `orders_df.describe(include="all")` digunakan untuk menampilkan **statistik deskriptif lengkap** dari seluruh kolom di DataFrame `orders_df`, baik kolom numerik maupun kolom kategorikal. Untuk kolom numerik, perintah ini menampilkan informasi seperti jumlah data (count), rata-rata (mean), standar deviasi (std), nilai minimum, maksimum, dan persentil. Untuk kolom kategorikal, ditampilkan jumlah kategori unik (unique), kategori yang paling sering muncul (top), dan frekuensinya (freq). Dengan perintah ini, kita mendapatkan gambaran lengkap mengenai karakteristik data pesanan secara keseluruhan.


Berdasarkan hasil tersebut, dapat diketahui bahwa rata-rata waktu pengiriman sebesar 14 hari dengan nilai maksimum sebesar 27 hari dan nilai minimum sebesar 1 hari.

**Eksplorasi Data orders_df dan customers_df**

Jika Anda perhatikan, pada data orders_df terdapat kolom yang berisi informasi terkait customer id pelanggan yang pernah melakukan order. Informasi ini bisa kita gunakan untuk mengidentifikasi pelanggan yang belum pernah melakukan order.

Untuk melakukan hal ini, kita bisa membuat sebuah kolom baru bernama “status” pada data customers_df. Kolom tersebut memiliki nilai “Active” untuk pelanggan yang pernah melakukan order setidaknya sekali dan sebaliknya bernilai “Non Active” untuk pelanggan yang belum pernah melakukan order sama sekali

In [ ]:
customer_id_in_orders_df =  orders_df.customer_id.tolist()
customers_df["status"] = customers_df["customer_id"].apply(lambda x: "Active" if x in customer_id_in_orders_df else "Non Active")
customers_df.sample(5)

customer_id customer_name             gender  age  \
292          293     fulan 293               Male   36   
495          495     fulan 495               Male   80   
892          888     fulan 888  Prefer not to say   22   
786          783     fulan 783             Female   49   
911          906     fulan 906  Prefer not to say   74   

                  home_address  zip_code           city  \
292   9227 Evans PlazaApt. 709      1391  Langworthfort   
495  1798 Schultz MewsApt. 704      9409   Lake Caitlin   
892   184 Joshua CrestApt. 140       968      Ellieland   
786     49 Lily RidgeSuite 143      4250  North Avabury   
911      748 Lucas WayApt. 482      3515      Ebertfurt   

                            state    country      status  
292                      Tasmania  Australia  Non Active  
495               New South Wales  Australia  Non Active  
892            Northern Territory  Australia  Non Active  
786               South Australia  Australia      Active  
911  Australian Capital Territory  Australia      Active

Kode tersebut digunakan untuk **menentukan status pelanggan** berdasarkan apakah mereka pernah melakukan pemesanan atau tidak. Pada baris pertama, `customer_id_in_orders_df = orders_df.customer_id.tolist()`, program mengambil seluruh nilai `customer_id` dari DataFrame `orders_df` dan mengubahnya menjadi sebuah **list**. List ini berisi daftar semua pelanggan yang pernah melakukan order.

Baris kedua, `customers_df["status"] = customers_df["customer_id"].apply(lambda x: "Active" if x in customer_id_in_orders_df else "Non Active")`, digunakan untuk membuat kolom baru bernama **status** pada `customers_df`. Setiap `customer_id` dicek: jika ID tersebut ada dalam list pelanggan yang pernah pesan, maka statusnya diberi label **"Active"**, dan jika tidak ada maka diberi label **"Non Active"**.

Baris terakhir, `customers_df.sample(5)`, menampilkan **5 baris acak** dari data pelanggan untuk melihat hasil penambahan kolom status tersebut. Dengan cara ini, kita bisa mengetahui pelanggan mana yang aktif dan tidak aktif berdasarkan riwayat transaksi mereka.


Kode di atas akan menghasilkan lima sample data, Bisa di ubah parameter 5 nya sesuai dengan keinginan untuk melihat data yg lebih banyak

Untuk memperoleh informasi terkait jumlah pelanggan yang berstatus “Active” dan “Non Active”, kita bisa menggunakan pivot table

In [ ]:
customers_df.groupby(by="status").customer_id.count()

status
Active        617
Non Active    384
Name: customer_id, dtype: int64

Kode `customers_df.groupby(by="status").customer_id.count()` digunakan untuk **menghitung jumlah pelanggan berdasarkan statusnya**, yaitu *Active* dan *Non Active*. Pertama, data dikelompokkan berdasarkan kolom `status` menggunakan `groupby(by="status")`. Lalu, `customer_id.count()` menghitung berapa banyak pelanggan yang termasuk dalam setiap kategori status tersebut. Hasil akhirnya adalah tabel ringkas yang menunjukkan jumlah pelanggan aktif dan tidak aktif dalam dataset.


Seperti yang terlihat pada pivot table di atas, terdapat cukup banyak pelanggan yang belum pernah melakukan transaksi sebelumnya. Ini tentunya merupakan data yg buruk karena hampir 30% pelanggan belum pernah melakukan order sebelumnya.

Untuk memperoleh lebih banyak informasi terkait kedua data tersebut, kita perlu menggabungkan keduanya melalui proses join atau merge. Berikut merupakan contoh kode untuk melakukan merge terhadap data orders_df dan customers_df.

In [ ]:
orders_customers_df = pd.merge(
    left=orders_df,
    right=customers_df,
    how="left",
    left_on="customer_id",
    right_on="customer_id"
)
orders_customers_df.head()

order_id  customer_id  payment order_date delivery_date  delivery_time  \
0         1           64    30811 2021-08-30    2021-09-24           25.0   
1         2          473    50490 2021-02-03    2021-02-13           10.0   
2         3          774    46763 2021-10-08    2021-11-03           26.0   
3         4          433    39782 2021-05-06    2021-05-19           13.0   
4         5          441    14719 2021-03-23    2021-03-24            1.0   

  customer_name             gender  age                   home_address  \
0      fulan 64  Prefer not to say   75      4927 Alice MeadowApt. 960   
1     fulan 473               Male   61  531 Schmitt BoulevardApt. 010   
2     fulan 774  Prefer not to say   34       2096 Wilson MewsApt. 714   
3     fulan 433  Prefer not to say   46        5777 Mayer PassApt. 881   
4     fulan 441  Prefer not to say   53   33 Richards JunctionApt. 478   

   zip_code                city              state    country  status  
0      7787      Sanfordborough    South Australia  Australia  Active  
1      1744             Annaton    South Australia  Australia  Active  
2      8590  West Jonathanshire           Tasmania  Australia  Active  
3      9728    West Michaelport           Tasmania  Australia  Active  
4      7650     South Rileyview  Western Australia  Australia  Active

Kode tersebut digunakan untuk menggabungkan dua DataFrame, yaitu **orders_df** dan **customers_df**, menjadi satu tabel baru bernama **orders_customers_df**. Proses penggabungan dilakukan dengan fungsi **pd.merge()** dari pandas. Parameter **left_on="customer_id"** dan **right_on="customer_id"** berarti kedua tabel digabung berdasarkan kolom yang sama, yaitu *customer_id*. Metode **how="left"** membuat penggabungan model *left join*, artinya seluruh baris dari **orders_df** tetap muncul meskipun mungkin tidak memiliki pasangan data pada **customers_df**. Jika ada kecocokan customer_id, maka data pelanggan akan ditambahkan ke baris pesanan yang sesuai; jika tidak ada, kolom dari tabel customers akan terisi nilai NaN. Terakhir, **orders_customers_df.head()** digunakan untuk menampilkan beberapa baris awal hasil gabungan tersebut.


Pada kode di atas, kita melakukan proses merge dengan metode “left join”.  metode ini memungkinkan kita untuk mengambil semua nilai dari tabel kiri serta nilai yang bersesuaian dengan tabel kanan.

Sehingga Terdapat banyak sekali informasi yang bisa kita eksplore dari data di atas. Berikut merupakan beberapa hal yang bisa dijelajahi.

**Jumlah order berdasarkan kota**
Kita bisa membuat pivot table untuk memperoleh informasi terkait jumlah order berdasarkan kota dengan kode seperti berikut

In [ ]:
orders_customers_df.groupby(by="city").order_id.nunique().sort_values(ascending=False).reset_index().head(10)

city  order_id
0        Jordanside         6
1           New Ava         6
2  Port Hannahburgh         5
3         Lake Rose         5
4        O'keefeton         5
5          East Max         5
6          Rubyfort         5
7          West Kai         5
8         Sarahstad         4
9        Russelstad         4

Kode tersebut digunakan untuk menganalisis data pesanan berdasarkan kota. Pertama, **orders_customers_df.groupby(by="city")** mengelompokkan data berdasarkan nama kota. Setelah dikelompokkan, **order_id.nunique()** menghitung jumlah *order_id* yang unik di tiap kota, sehingga kamu bisa tahu berapa banyak pesanan yang terjadi di masing-masing kota. Kemudian, **sort_values(ascending=False)** mengurutkan hasilnya dari kota dengan jumlah pesanan terbanyak ke yang paling sedikit. Setelah itu, **reset_index()** digunakan agar hasil pengelompokan kembali menjadi DataFrame yang rapi dan mudah dibaca. Terakhir, **head(10)** menampilkan 10 kota teratas dengan jumlah pesanan terbanyak.


berdasarkan hasil tersebut, diketahui bahwa kota Jordanside dan New Ava merupakan dua kota yang memiliki jumlah order terbanyak.

Jumlah order berdasarkan state
Sekarang kita akan melihat jumlah order berdasarkan state. Untuk memperoleh informasi terkait hal ini, kita juga bisa menggunakan pivot table. Gunakan kode di bawah ini untuk menerapkannya.

In [ ]:
orders_customers_df.groupby(by="state").order_id.nunique().sort_values(ascending=False)

state
South Australia                 148
Queensland                      139
Western Australia               130
New South Wales                 129
Victoria                        118
Australian Capital Territory    118
Tasmania                        112
Northern Territory              106
Name: order_id, dtype: int64

Kode tersebut digunakan untuk melihat jumlah pesanan unik (*order_id*) di setiap **state**. Pertama, **orders_customers_df.groupby(by="state")** mengelompokkan data berdasarkan kolom *state*. Setelah itu, **order_id.nunique()** menghitung berapa banyak *order_id* yang berbeda di tiap state, sehingga kamu bisa mengetahui jumlah pesanan di masing-masing wilayah. Kemudian, **sort_values(ascending=False)** mengurutkan hasilnya dari state dengan pesanan terbanyak ke yang paling sedikit. Hasil akhirnya adalah daftar state yang sudah terurut berdasarkan jumlah pesanan unik yang mereka miliki.


Kode tersebut akan menghasilkan pivot table seperti di bawah ini. Berdasarkan pivot table tersebut, diketahui bahwa South Australia merupakan state yang paling banyak melakukan order.

Jumlah order berdasarkan gender
Informasi selanjutnya yang dapat kita eksplorasi adalah jumlah order berdasarkan gender. Untuk melakukan hal ini, tentunya kita perlu membuat sebuah pivot table menggunakan kode berikut.


In [ ]:
orders_customers_df.groupby(by="gender").order_id.nunique().sort_values(ascending=False)

gender
Prefer not to say    716
Female               139
Male                 136
Name: order_id, dtype: int64

Kode tersebut berfungsi untuk mengetahui jumlah pesanan unik (*order_id*) berdasarkan **gender** pelanggan. Pertama, **orders_customers_df.groupby(by="gender")** mengelompokkan data sesuai jenis kelamin. Setelah itu, **order_id.nunique()** menghitung berapa banyak pesanan berbeda yang dibuat oleh masing-masing kelompok gender. Kemudian, **sort_values(ascending=False)** mengurutkan hasilnya dari gender dengan jumlah pesanan paling banyak hingga yang paling sedikit. Hasil akhirnya menunjukkan perbandingan aktivitas pemesanan berdasarkan gender secara jelas dan terurut.


Berdasarkan hasil tersebut, dapat dilihat bahwa kebanyakan order dilakukan oleh pelanggan yang berjenis kelamin prefer not to say. Hal ini tentunya sejalan dengan jumlah pelanggan yang kebanyakan dari kelompok gender tersebut.


**Jumlah order berdasarkan kelompok usia**

Mengeksplorasi jumlah order berdasarkan kelompok usia. Untuk melakukan hal ini, kita perlu mendefinisikan sebuah kolom baru bernama “age_group”. Kolom ini akan membantu kita dalam mengelompokkan pelanggan ke dalam tiga kelompok, yaitu youth, adults, dan seniors. Selanjutnya, buatlah pivot table berdasarkan hal tersebut menggunakan contoh kode di bawah ini.

In [ ]:
orders_customers_df["age_group"] = orders_customers_df.age.apply(lambda x: "Youth" if x <= 24 else ("Seniors" if x > 64 else "Adults"))

Kode tersebut digunakan untuk membuat kolom baru bernama **age_group** pada DataFrame **orders_customers_df**. Kolom ini berisi kategori umur berdasarkan nilai pada kolom **age**. Fungsi **apply()** menjalankan *lambda function* untuk setiap nilai usia. Aturannya adalah: jika usia **≤ 24**, maka dikategorikan sebagai **"Youth"**; jika usia **> 64**, maka masuk kategori **"Seniors"**; sedangkan usia di antara dua rentang tersebut otomatis masuk kategori **"Adults"**. Dengan cara ini, data usia yang sebelumnya berupa angka berubah menjadi kelompok umur yang lebih mudah dianalisis.


In [ ]:
orders_customers_df.groupby(by="age_group").order_id.nunique().sort_values(ascending=False)

age_group
Adults     681
Seniors    226
Youth       93
Name: order_id, dtype: int64

Kode tersebut digunakan untuk melihat jumlah pesanan unik (*order_id*) berdasarkan kelompok umur yang sebelumnya sudah dibuat dalam kolom **age_group**. Pertama, **orders_customers_df.groupby(by="age_group")** mengelompokkan data ke dalam tiga kategori: *Youth*, *Adults*, dan *Seniors*. Setelah dikelompokkan, **order_id.nunique()** menghitung berapa banyak pesanan berbeda yang dilakukan oleh masing-masing kelompok umur. Lalu, **sort_values(ascending=False)** mengurutkan hasilnya dari kelompok umur dengan jumlah pesanan terbanyak hingga yang paling sedikit. Hasil akhirnya menunjukkan kelompok umur mana yang paling aktif melakukan pemesanan.


Berdasarkan hasil tersebut diketahui bahwa pelanggan yang paling banyak melakukan order berasal dari kelompok usia Adults.

sejauh ini kita telah menemukan banyak sekali informasi yang tentunya menarik untuk ditelusuri lebih dalam. Namun, sebelum itu mari kita mengeksplorasi dua data yang lain (product_df dan sales_df) terlebih dahulu.

**Eksplorasi Data product_df dan sales_df**


Pada tahap ini, kita akan mengeksplorasi data product_df dan sales_df. Sebagai permulaan, kita dapat melihat rangkuman parameter statistik dari keduanya menggunakan method describe().

In [ ]:
products_df.describe(include="all")


product_id product_type product_name  size colour        price  \
count   1260.000000         1260         1260  1260   1260  1260.000000   
unique          NaN            3           35     8      7          NaN   
top             NaN        Shirt        Denim    XS    red          NaN   
freq            NaN          420           70   252    180          NaN   
mean     629.500000          NaN          NaN   NaN    NaN   105.805556   
std      363.874979          NaN          NaN   NaN    NaN     9.704423   
min        0.000000          NaN          NaN   NaN    NaN    90.000000   
25%      314.750000          NaN          NaN   NaN    NaN    95.750000   
50%      629.500000          NaN          NaN   NaN    NaN   108.500000   
75%      944.250000          NaN          NaN   NaN    NaN   114.000000   
max     1259.000000          NaN          NaN   NaN    NaN   119.000000   

           quantity                                        description  
count   1260.000000                                               1260  
unique          NaN                                               1260  
top             NaN  A violet coloured, XL sized, Tracksuit Bottoms...  
freq            NaN                                                  1  
mean      60.150000                                                NaN  
std       11.670573                                                NaN  
min       40.000000                                                NaN  
25%       50.000000                                                NaN  
50%       60.000000                                                NaN  
75%       70.000000                                                NaN  
max       80.000000                                                NaN

Kode **products_df.describe(include="all")** digunakan untuk menampilkan ringkasan statistik dari seluruh kolom yang ada di DataFrame **products_df**, baik kolom numerik maupun kolom kategori. Biasanya, fungsi **describe()** hanya menampilkan statistik untuk data numerik saja, tetapi dengan menambahkan **include="all"**, pandas akan menyertakan semua tipe data. Hasilnya bisa mencakup informasi seperti jumlah data (*count*), nilai unik (*unique*), nilai yang paling sering muncul (*top*), frekuensi kemunculan nilai tersebut (*freq*), serta statistik numerik seperti *mean*, *min*, *max*, dan *quartiles* untuk kolom yang berisi angka. Dengan satu perintah ini, kamu bisa mendapatkan gambaran umum tentang isi dan karakteristik data produk secara cepat dan lengkap.


In [ ]:
sales_df.describe(include="all")

sales_id     order_id   product_id  price_per_unit    quantity  \
count  5000.000000  5000.000000  5000.000000     5000.000000  5000.00000   
mean   2499.500000   503.038200   634.053200      103.501600     1.99240   
std    1443.520003   285.964418   363.255794        9.195004     0.80751   
min       0.000000     1.000000     1.000000       90.000000     1.00000   
25%    1249.750000   258.000000   323.000000       95.000000     1.00000   
50%    2499.500000   504.500000   635.000000      102.000000     2.00000   
75%    3749.250000   749.000000   951.000000      112.000000     3.00000   
max    4999.000000   999.000000  1259.000000      119.000000     3.00000   

       total_price  
count  5000.000000  
mean    206.360000  
std      86.357457  
min      90.000000  
25%     112.000000  
50%     204.000000  
75%     285.000000  
max     357.000000

Kode **sales_df.describe(include="all")** digunakan untuk menampilkan ringkasan statistik dari seluruh kolom di DataFrame **sales_df**, baik kolom angka maupun kolom kategori. Secara default, **describe()** hanya menampilkan statistik untuk data numerik, tetapi dengan menambahkan **include="all"**, pandas akan menyertakan semua tipe data. Hasilnya bisa mencakup jumlah data (*count*), jumlah nilai unik (*unique*), nilai yang paling sering muncul (*top*) beserta frekuensinya (*freq*), serta statistik numerik seperti *mean*, *min*, *max*, dan *quartiles* untuk kolom angka. Dengan perintah ini, kamu bisa mendapatkan gambaran umum tentang karakteristik data penjualan secara menyeluruh hanya dalam satu langkah.


Berdasarkan hasil tersebut, dapat dilihat bahwa harga barang yang dijual berkisar antara 90 hingga 119 dolar. Selain itu, kita juga memperoleh informasi lain yang tidak kalah menarik yaitu pada setiap transaksi pelanggan paling banyak membeli tiga buah item dalam satu jenis produk dengan total harga sebesar 357 dolar.

Apabila Anda penasaran dengan produk yang memiliki harga termahal dan terendah, silakan jalankan kode berikut untuk melihatnya.

In [ ]:
products_df.sort_values(by="price", ascending=False)

product_id product_type product_name size  colour  price  quantity  \
671          665       Jacket        Parka   XS     red    119        65   
672          666       Jacket        Parka    S     red    119        66   
673          667       Jacket        Parka    M     red    119        56   
674          668       Jacket        Parka    L     red    119        73   
675          669       Jacket        Parka   XL     red    119        64   
...          ...          ...          ...  ...     ...    ...       ...   
1222        1216     Trousers      Pleated    S  indigo     90        41   
1229        1223     Trousers      Pleated    L  violet     90        48   
1228        1222     Trousers      Pleated    M  violet     90        45   
1227        1221     Trousers      Pleated    S  violet     90        50   
1226        1220     Trousers      Pleated   XS  violet     90        58   

                                        description  
671          A red coloured, XS sized, Parka Jacket  
672           A red coloured, S sized, Parka Jacket  
673           A red coloured, M sized, Parka Jacket  
674           A red coloured, L sized, Parka Jacket  
675          A red coloured, XL sized, Parka Jacket  
...                                             ...  
1222   A indigo coloured, S sized, Pleated Trousers  
1229   A violet coloured, L sized, Pleated Trousers  
1228   A violet coloured, M sized, Pleated Trousers  
1227   A violet coloured, S sized, Pleated Trousers  
1226  A violet coloured, XS sized, Pleated Trousers  

[1260 rows x 8 columns]

Kode **products_df.sort_values(by="price", ascending=False)** digunakan untuk mengurutkan data pada DataFrame **products_df** berdasarkan kolom **price**. Parameter **ascending=False** berarti pengurutan dilakukan dari harga yang paling tinggi ke harga yang paling rendah. Hasilnya adalah tabel produk yang sudah tersusun mulai dari produk termahal hingga termurah, sehingga memudahkan kamu melihat atau menganalisis produk dengan harga terbesar terlebih dahulu.



Selanjutnya, kita bisa menggunakan pivot table untuk mencari informasi terkait produk berdasarkan tipe dan nama produknya. Berikut contoh kode yang bisa Anda gunakan.

In [ ]:
products_df.groupby(by="product_type").agg({
    "product_id": "nunique",
    "quantity": "sum",
    "price":  ["min", "max"]
})

product_id quantity price     
                nunique      sum   min  max
product_type                               
Jacket              420    25387    90  119
Shirt               420    25263    92  119
Trousers            420    25139    90  119

Kode tersebut digunakan untuk melakukan analisis data produk berdasarkan jenis produk (*product_type*) dengan cara mengelompokkan dan menghitung beberapa nilai statistik sekaligus. Pertama, **products_df.groupby(by="product_type")** mengelompokkan data berdasarkan tipe produk. Setelah itu, fungsi **agg()** digunakan untuk menerapkan beberapa perhitungan dalam satu langkah. Pada kolom **product_id**, digunakan **"nunique"** untuk menghitung berapa banyak produk berbeda dalam setiap kategori. Pada kolom **quantity**, digunakan **"sum"** untuk menjumlahkan total kuantitas produk yang tersedia per kategori. Sedangkan pada kolom **price**, digunakan **"min"** dan **"max"** untuk mengetahui harga termurah dan termahal dari setiap tipe produk. Hasil akhirnya adalah tabel ringkas yang menunjukkan jumlah variasi produk, total stok, serta rentang harga dalam setiap kelompok produk.


In [ ]:
products_df.groupby(by="product_name").agg({
    "product_id": "nunique",
    "quantity": "sum",
    "price": ["min", "max"]
})

product_id quantity price     
                     nunique      sum   min  max
product_name                                    
Bomber                    35     2083    90   90
Camp Collared             35     2071   112  112
Cardigan                  35     2032   118  118
Cargo Pants               35     2146   106  106
Casual Slim Fit           35     2086   113  113
Chambray                  35     2020   105  105
Chinos                    35     2101   100  100
Coach                     35     2158   115  115
Cords                     35     2260   113  113
Cropped                   35     2085    99   99
Cuban Collar              35     2017    93   93
Denim                     70     4204    92  115
Drawstring                35     2042   104  104
Dress                     35     2125   119  119
Flannel                   35     2135    96   96
Henley                    35     2051    92   92
High-Waisted              35     2198    98   98
Joggers                   35     2107    94   94
Leather                   35     2276   113  113
Linen                     35     2138   116  116
Mandarin Collar           35     2203   108  108
Oxford Cloth              35     2071   114  114
Parka                     35     2201   119  119
Peacoat                   35     2067   102  102
Pleated                   35     2030    90   90
Polo                      35     2196   117  117
Puffer                    35     1946   110  110
Pullover                  35     2184   114  114
Relaxed Leg               35     2002    95   95
Shearling                 35     2169    95   95
Slim-Fit                  35     2155   119  119
Tracksuit Bottoms         35     2038    91   91
Trench Coat               35     2132   112  112
Windbreaker               35     2085   109  109
Wool                      35     1975   111  111

Kode tersebut digunakan untuk menganalisis data berdasarkan **nama produk** (*product_name*) dengan menghitung beberapa nilai statistik penting sekaligus. Pertama, **products_df.groupby(by="product_name")** mengelompokkan data menurut setiap nama produk. Setelah itu, fungsi **agg()** dipakai untuk menerapkan beberapa jenis perhitungan dalam satu langkah. Pada kolom **product_id**, digunakan **"nunique"** untuk menghitung berapa banyak ID produk yang berbeda dalam satu nama produk (berguna jika satu nama punya beberapa varian). Pada kolom **quantity**, digunakan **"sum"** untuk menjumlahkan total jumlah/ stok yang tersedia untuk produk tersebut. Sementara pada kolom **price**, digunakan **"min"** dan **"max"** untuk menampilkan harga terendah dan tertinggi dari produk tersebut. Hasil akhirnya adalah tabel ringkas yang menampilkan jumlah varian produk, total stok, serta rentang harga untuk setiap nama produk secara lengkap.


Pivot table di atas dapat memberikan kita gambaran terkait produk yang dijual oleh Fashion Collection.

Sebagai calon praktisi data yang Andal, tentunya Anda penasaran dengan produk yang paling laris. Nah, untuk menjawab pertanyaan ini, kita perlu menyatukan (merge) tabel product_df dan sales_df dengan kode berikut.

In [ ]:
sales_products_df = pd.merge(
    left=sales_df,
    right=products_df,
    how="left",
    left_on="product_id",
    right_on="product_id"
)
sales_products_df.head()

sales_id  order_id  product_id  price_per_unit  quantity_x  total_price  \
0         0         1         218             106           2          212   
1         1         1         481             118           1          118   
2         2         1           2              96           3          288   
3         3         1        1002             106           2          212   
4         4         1         691             113           3          339   

  product_type  product_name size  colour  price  quantity_y  \
0        Shirt      Chambray    L  orange    105          44   
1       Jacket        Puffer    S  indigo    110          62   
2        Shirt  Oxford Cloth    M     red    114          54   
3     Trousers          Wool    M    blue    111          52   
4       Jacket         Parka    S  indigo    119          53   

                                   description  
0   A orange coloured, L sized, Chambray Shirt  
1    A indigo coloured, S sized, Puffer Jacket  
2  A red coloured, M sized, Oxford Cloth Shirt  
3      A blue coloured, M sized, Wool Trousers  
4     A indigo coloured, S sized, Parka Jacket

Kode tersebut digunakan untuk menggabungkan dua DataFrame, yaitu **sales_df** dan **products_df**, menjadi satu tabel baru bernama **sales_products_df**. Penggabungan dilakukan menggunakan **pd.merge()** dengan metode **left join**, artinya semua baris dari **sales_df** akan tetap muncul walaupun tidak ada pasangan data yang cocok di **products_df**. Penggabungan dilakukan berdasarkan kolom **product_id**, sehingga informasi penjualan pada **sales_df** akan dilengkapi dengan detail produk dari **products_df**. Jika terdapat kecocokan product_id, maka data produk akan ditambahkan ke baris penjualan yang sesuai; jika tidak ada kecocokan, kolom dari produk akan berisi NaN. Perintah **sales_products_df.head()** kemudian menampilkan beberapa baris pertama dari hasil penggabungan tersebut.


Pada dasarnya kode di atas akan melakukan proses merge terhadap data product_df dan sales_df. Proses merge tersebut dilakukan menggunakan metode “left”. Berikut hasil dari proses merge tersebut.

jika diperhatikan kembali, hasil dari proses merge di atas memiliki perbedaan antara nilai price_per_unit dan price. Hal ini bisa terjadi karena adanya potongan harga, biaya operasional, dan biaya lainnya.

sekarang kita coba melihat informasi penjualan produk berdasarkan tipenya.
dengan membuat pivot table berdasarkan produk type dengan kode berikut

In [ ]:
sales_products_df.groupby(by="product_type").agg({
    "sales_id": "nunique",
    "quantity_x": "sum",
    "total_price": "sum"
})

sales_id  quantity_x  total_price
product_type                                   
Jacket            1676        3343       357026
Shirt             1641        3259       333600
Trousers          1683        3360       341174

Kode tersebut digunakan untuk menganalisis data penjualan berdasarkan **jenis produk** (*product_type*) setelah tabel penjualan dan produk digabungkan. Pertama, **sales_products_df.groupby(by="product_type")** mengelompokkan seluruh data penjualan berdasarkan tipe produk. Kemudian, fungsi **agg()** digunakan untuk menghitung beberapa nilai sekaligus. Pada kolom **sales_id**, digunakan **"nunique"** untuk menghitung berapa banyak transaksi penjualan yang berbeda pada setiap jenis produk. Pada kolom **quantity_x**, digunakan **"sum"** untuk menghitung total jumlah barang yang terjual untuk tiap product_type. Sementara itu, **"total_price": "sum"** menjumlahkan total pendapatan yang dihasilkan dari tiap kategori produk. Hasil akhir berupa tabel ringkas yang menunjukkan jumlah transaksi, total unit terjual, dan total pemasukan berdasarkan jenis produk.


Jika Anda perhatikan pivot table di atas, Trousers merupakan tipe produk yang paling laris. Akan tetapi, jika dilihat berdasarkan revenue yang diterima, Jacket merupakan tipe produk yang paling banyak menyumbang revenue perusahaan.

membuat pivot table yang sama untuk melihat informasi penjualan berdasarkan nama produk menggunakan kode di bawah ini

In [ ]:
sales_products_df.groupby(by="product_name").agg({
    "sales_id": "nunique",
    "quantity_x": "sum",
    "total_price": "sum"
}).sort_values(by="total_price", ascending=False)

sales_id  quantity_x  total_price
product_name                                        
Denim                   273         527        52399
Casual Slim Fit         154         306        36414
Trench Coat             146         299        35581
Shearling               150         302        35334
Puffer                  140         298        35164
Flannel                 141         281        33158
Cropped                 135         284        32660
Pleated                 147         308        32340
Joggers                 164         334        31062
Chambray                141         290        30740
Parka                   134         269        30397
Bomber                  150         297        29700
Chinos                  135         260        29380
Windbreaker             143         287        29274
Cardigan                134         260        29120
Peacoat                 132         266        28994
Tracksuit Bottoms       130         257        28784
Slim-Fit                154         288        27936
Oxford Cloth            146         289        27744
Drawstring              147         288        27648
High-Waisted            140         278        27522
Camp Collared           139         279        27342
Cargo Pants             134         267        27234
Relaxed Leg             146         301        27090
Cuban Collar            122         254        26670
Henley                  146         281        26414
Wool                    125         249        26394
Leather                 136         263        25774
Mandarin Collar         124         236        25724
Dress                   127         243        25272
Pullover                143         276        25116
Polo                    131         264        25080
Coach                   134         265        24645
Linen                   131         270        24570
Cords                   126         246        23124

Kode tersebut digunakan untuk menganalisis penjualan berdasarkan **nama produk** (*product_name*) dan melihat produk mana yang menghasilkan pendapatan terbesar. Pertama, **sales_products_df.groupby(by="product_name")** mengelompokkan seluruh data penjualan sesuai nama produk. Setelah itu, fungsi **agg()** menghitung beberapa nilai sekaligus: **"sales_id": "nunique"** untuk mengetahui jumlah transaksi unik per produk, **"quantity_x": "sum"** untuk menghitung total jumlah unit produk yang terjual, dan **"total_price": "sum"** untuk menjumlahkan total pendapatan dari masing-masing produk. Selanjutnya, **sort_values(by="total_price", ascending=False)** mengurutkan hasil analisis dari produk dengan pendapatan tertinggi sampai terendah. Hasil akhirnya adalah daftar produk yang menunjukkan transaksi terbanyak, jumlah unit terjual, dan pendapatan terbesar secara terurut.


Berdasarkan pivot table tersebut, diketahui bahwa produk Denim merupakan produk yang paling laris dan juga paling banyak menyumbang revenue terhadap perusahaan.  

**Eksplorasi Data all_df**

kita perlu membuat sebuah DataFrame baru bernama all_df untuk menampung semua informasi dari keempat tabel yang kita miliki. Berikut contoh kode yang dapat kita gunakan untuk menjalankan proses penggabungan ini.

In [ ]:
all_df = pd.merge(
    left=sales_products_df,
    right=orders_customers_df,
    how="left",
    left_on="order_id",
    right_on="order_id"
)
all_df.head()

sales_id  order_id  product_id  price_per_unit  quantity_x  total_price  \
0         0         1         218             106           2          212   
1         1         1         481             118           1          118   
2         2         1           2              96           3          288   
3         3         1        1002             106           2          212   
4         4         1         691             113           3          339   

  product_type  product_name size  colour  ...  customer_name  \
0        Shirt      Chambray    L  orange  ...       fulan 64   
1       Jacket        Puffer    S  indigo  ...       fulan 64   
2        Shirt  Oxford Cloth    M     red  ...       fulan 64   
3     Trousers          Wool    M    blue  ...       fulan 64   
4       Jacket         Parka    S  indigo  ...       fulan 64   

              gender age               home_address  zip_code            city  \
0  Prefer not to say  75  4927 Alice MeadowApt. 960      7787  Sanfordborough   
1  Prefer not to say  75  4927 Alice MeadowApt. 960      7787  Sanfordborough   
2  Prefer not to say  75  4927 Alice MeadowApt. 960      7787  Sanfordborough   
3  Prefer not to say  75  4927 Alice MeadowApt. 960      7787  Sanfordborough   
4  Prefer not to say  75  4927 Alice MeadowApt. 960      7787  Sanfordborough   

             state    country  status age_group  
0  South Australia  Australia  Active   Seniors  
1  South Australia  Australia  Active   Seniors  
2  South Australia  Australia  Active   Seniors  
3  South Australia  Australia  Active   Seniors  
4  South Australia  Australia  Active   Seniors  

[5 rows x 28 columns]

Kode tersebut digunakan untuk menggabungkan dua DataFrame yang sebelumnya sudah digabung, yaitu **sales_products_df** dan **orders_customers_df**, menjadi satu tabel lengkap bernama **all_df**. Penggabungan dilakukan dengan **pd.merge()** menggunakan metode **left join**, sehingga semua baris dari **sales_products_df** akan tetap muncul meskipun tidak ada data yang cocok di **orders_customers_df**. Penggabungan dilakukan berdasarkan kolom **order_id**, sehingga setiap data penjualan akan dilengkapi dengan informasi detail pesanan serta data pelanggan. Jika ada *order_id* yang cocok, informasi pelanggan dan order akan ditambahkan; jika tidak cocok, kolom dari tabel orders_customers_df akan berisi NaN. Perintah **all_df.head()** kemudian menampilkan beberapa baris awal dari tabel gabungan lengkap tersebut.


Proses merge di atas akan menghasilkan DataFrame seperti hasil di atas

Selanjutnya, mari kita coba lihat preferensi pembelian berdasarkan state pelanggan dan tipe produk menggunakan kode di bawah ini.

In [ ]:
all_df.groupby(by=["state", "product_type"]).agg({
    "quantity_x": "sum",
    "total_price": "sum"
})

quantity_x  total_price
state                        product_type                         
Australian Capital Territory Jacket               406        43204
                             Shirt                396        40448
                             Trousers             454        46790
New South Wales              Jacket               451        47998
                             Shirt                431        43980
                             Trousers             392        39766
Northern Territory           Jacket               365        38991
                             Shirt                336        33865
                             Trousers             384        38998
Queensland                   Jacket               499        53511
                             Shirt                417        42506
                             Trousers             453        46045
South Australia              Jacket               461        49090
                             Shirt                509        52685
                             Trousers             455        46041
Tasmania                     Jacket               412        44370
                             Shirt                387        39668
                             Trousers             379        38057
Victoria                     Jacket               359        38203
                             Shirt                390        40206
                             Trousers             414        41948
Western Australia            Jacket               390        41659
                             Shirt                393        40242
                             Trousers             429        43529

Kode tersebut digunakan untuk menganalisis data penjualan secara lebih detail berdasarkan **state** dan **product_type** secara bersamaan. Pertama, **all_df.groupby(by=["state", "product_type"])** mengelompokkan data menurut kombinasi dua kategori: wilayah (*state*) dan jenis produk (*product_type*). Setelah data dikelompokkan, fungsi **agg()** menghitung dua nilai penting: **"quantity_x": "sum"** untuk menjumlahkan total unit produk yang terjual dalam setiap kombinasi state–product_type, serta **"total_price": "sum"** untuk menghitung total pendapatan yang dihasilkan dari kombinasi tersebut. Hasil akhirnya berupa tabel ringkas yang menunjukkan berapa banyak produk terjual dan berapa pendapatan yang dihasilkan di setiap state untuk setiap jenis produk, sehingga analisis penjualan menjadi lebih terperinci dan mudah dibandingkan.


Pivot table di atas memberikan kita gambaran terkait tipe produk yang disukai pengguna berdasarkan lokasi negara bagiannya. Jika diperhatikan, tipe produk Jacket (garis merah) paling banyak terjual pada negara bagian Queensland, South Australia, dan New South Wales. Untuk tipe produk lain, Anda bisa melihatnya pada gambar pivot table di atas.

Sekarang Anda bisa melakukan hal yang sama untuk mengetahui selera tipe produk pelanggan berdasarkan gender dan kelompok usia. Berikut contoh kode yang bisa Anda gunakan.

In [ ]:
all_df.groupby(by=["gender", "product_type"]).agg({
    "quantity_x": "sum",
    "total_price": "sum"
})

quantity_x  total_price
gender            product_type                         
Female            Jacket               481        50963
                  Shirt                445        45146
                  Trousers             481        49295
Male              Jacket               480        50978
                  Shirt                410        41939
                  Trousers             453        46071
Prefer not to say Jacket              2349       251486
                  Shirt               2386       244765
                  Trousers            2400       243092

Kode tersebut digunakan untuk menganalisis penjualan dengan melihat hubungan antara **gender pelanggan** dan **jenis produk** (*product_type*). Pertama, **all_df.groupby(by=["gender", "product_type"])** mengelompokkan data berdasarkan kombinasi gender dan tipe produk. Setelah dikelompokkan, fungsi **agg()** menghitung dua hal penting: **"quantity_x": "sum"** untuk mengetahui total jumlah unit produk yang dibeli oleh masing-masing gender pada tiap jenis produk, dan **"total_price": "sum"** untuk mengetahui total pendapatan yang dihasilkan dari kombinasi tersebut. Hasilnya adalah tabel yang menunjukkan pola pembelian berdasarkan gender untuk setiap tipe produk, sehingga kamu bisa melihat gender mana yang lebih aktif membeli produk tertentu dan seberapa besar pendapatannya.


In [ ]:
all_df.groupby(by=["age_group", "product_type"]).agg({
    "quantity_x": "sum",
    "total_price": "sum"
})

quantity_x  total_price
age_group product_type                         
Adults    Jacket              2292       245055
          Shirt               2225       227781
          Trousers            2272       231271
Seniors   Jacket               777        82959
          Shirt                733        74977
          Trousers             766        77471
Youth     Jacket               274        29012
          Shirt                301        30842
          Trousers             322        32432

Kode tersebut digunakan untuk menganalisis penjualan berdasarkan **kelompok umur** (*age_group*) dan **jenis produk** (*product_type*). Pertama, **all_df.groupby(by=["age_group", "product_type"])** mengelompokkan data sesuai kombinasi kategori umur (Youth, Adults, Seniors) dan tipe produk. Setelah data terbagi dalam kelompok-kelompok tersebut, fungsi **agg()** digunakan untuk menghitung dua hal penting: **"quantity_x": "sum"** untuk menjumlahkan total unit produk yang dibeli oleh setiap kelompok umur pada masing-masing jenis produk, dan **"total_price": "sum"** untuk menghitung total pendapatan yang dihasilkan dari kombinasi tersebut. Hasil akhirnya memberikan gambaran jelas tentang kelompok umur mana yang paling banyak membeli tipe produk tertentu dan kontribusi pendapatannya masing-masing.


pivot table di atas dapat memberikan kita gambaran terkait selera tipe produk pelanggan berdasarkan gender dan kelompok usia. Semua informasi ini akan sangat membantu Anda dalam menjawab pertanyaan terkait preferensi pengguna berdasarkan demografinya.

**Tugas**

Jawablah beberapa pertanyaan berikut ini berdasarkan EDA yang sudah di lakukan

1. Bagaimana performa penjualan dan revenue perusahaan dalam beberapa bulan terakhir?
2. Produk apa yang paling banyak dan paling sedikit terjual?
3. Bagaimana demografi pelanggan yang kita miliki?
4. Kapan terakhir pelanggan melakukan transaksi?
5. Seberapa sering seorang pelanggan melakukan pembelian dalam beberapa bulan terakhir?
6. Berapa banyak uang yang dihabiskan pelanggan dalam beberapa bulan terakhir?.

**jawaban:**

1. Penjualan perusahaan menunjukkan kinerja yang cukup kuat dan konsisten dalam beberapa bulan terakhir. Jumlah transaksi tersebar dengan baik di berbagai jenis produk seperti Jacket, Shirt, dan Trousers. Pendapatan yang diperoleh juga tergolong tinggi, terutama dari produk dengan kisaran harga menengah hingga premium. Tidak terlihat adanya penurunan yang berarti, sehingga dapat dikatakan bahwa performa penjualan tetap stabil.

2. Untuk kategori produk, item yang mencatat jumlah transaksi dan pendapatan terbesar adalah Jacket, Shirt, dan Trousers, dengan performa penjualan yang cenderung seimbang di antara ketiganya. Jika dianalisis berdasarkan nama produk, Denim menjadi penyumbang revenue tertinggi, disusul oleh Casual Slim Fit dan Trench Coat. Sementara itu, produk yang mencatat penjualan paling rendah adalah Cords, serta beberapa jenis pakaian seperti Coach dan Linen, yang menunjukkan angka revenue terendah.

3. Dari sisi gender, sebagian besar pelanggan memilih opsi “Prefer not to say”, kemudian diikuti oleh pelanggan berjenis kelamin Female dan Male.
Untuk usia, kelompok Adults (25–64 tahun) menjadi yang paling dominan dalam melakukan pembelian. Kelompok Seniors berada di urutan berikutnya, sementara Youth merupakan segmen dengan kontribusi paling kecil.
Dilihat dari lokasi, pelanggan tersebar di berbagai wilayah di Australia. Penjualan tertinggi berasal dari South Australia, disusul oleh Queensland dan Western Australia.

4. Berdasarkan data pesanan, aktivitas transaksi pelanggan tercatat berlangsung hingga penghujung tahun 2021. Dengan demikian, sebagian besar pelanggan terakhir kali melakukan pembelian pada periode tersebut.

5. Secara umum, frekuensi pembelian pelanggan berada pada tingkat rendah hingga menengah. Kebanyakan pelanggan hanya melakukan sekitar 1–2 transaksi unik, sehingga menunjukkan bahwa jumlah pesanan per pelanggan tidak terlalu tinggi.

6. Secara umum, pelanggan membelanjakan sekitar $100–$300 untuk setiap transaksi, bergantung pada jenis produk yang dibeli serta jumlahnya. Kelompok Adults menjadi penyumbang revenue terbesar bagi perusahaan, menunjukkan daya beli yang lebih tinggi dibanding kelompok lain. Sementara itu, pelanggan dalam kategori Seniors dan Youth cenderung mengeluarkan jumlah yang lebih kecil dibandingkan kelompok Adults.